### ISSUE TITLE
Can't download video

### ISSUE THREAD

**Issue by kojuice182** [TalhaMangarah/tiktok-downloader-ios-shortcut#2]
Keep showing "No URL specified, make sure to pass a valid URL to the Get Contents of URL action."

**Comment by TalhaMangarah** [comment]
Updated the shortcut. Please let me know if it's working now.
Download link: 

- https://www.icloud.com/shortcuts/83f661ac621e4ea5b81e4d33092e93d0

**Comment by whoisarod** [comment]
Error message "Can't connect to gallery"

**Comment by kojuice182** [comment]
> Updated the shortcut. Please let me know if it's working now. Download link:
> 
> * https://www.icloud.com/shortcuts/83f661ac621e4ea5b81e4d33092e93d0

It's working now, thank you.
